# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "test-remote-backend-za7uripb"
    encrypt = true
    key     = "dev/terraform.tfstate"
    region  = "ap-southeast-1"
  }
}
